version: '3.8'

services:
  kea-dhcp6:
    build: .
    network_mode: host
    container_name: kea-dhcp6
    volumes:
      - ./kea.conf:/etc/kea/kea.conf  # optional, if you want to use a local config
      - /var/log/kea:/var/log/kea
      - /var/lib/kea:/var/lib/kea 
